/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Controller.KhachHangController;
import Entity.KhachHang;
import java.sql.Date;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author giang
 */
public class Khachhang extends javax.swing.JPanel {

    /**
     * Creates new form Khachhang
     */
    public Khachhang() {
        initComponents();
        loadTable();
         addSearchEvent();
    }
    private KhachHangController controller = new KhachHangController();

private void loadTable()  {
    List<KhachHang> list = controller.getAllKhachHang();
    DefaultTableModel model = (DefaultTableModel) tblKhachhang.getModel();

    
    model.setColumnIdentifiers(new Object[]{
        "Mã KH", "Tên KH", "SĐT", "Địa chỉ", "Giới tính", "Ngày sinh", "Ghi chú"
    });

    model.setRowCount(0); // Xóa dữ liệu cũ

    for (KhachHang kh : list) {
        model.addRow(new Object[]{
            kh.getMakh(),
            kh.getTenkh(),
            kh.getSdt(),
            kh.getDiachi(),
            kh.getGioitinh(),
            kh.getNgaysinh(),
            kh.getGhichu()
        });
    }
    
}

private void search() throws SQLException {
    String keyword = txtSearch.getText().trim();
    List<KhachHang> list = controller.getALl(keyword);
    loadToTable(list);
}

private void loadToTable(List<KhachHang> list) {
    DefaultTableModel model = (DefaultTableModel) tblKhachhang.getModel();
    model.setRowCount(0);

    for (KhachHang kh : list) {
        model.addRow(new Object[]{
            kh.getMakh(),
            kh.getTenkh(),
            kh.getSdt(),
            kh.getDiachi(),
            kh.getGioitinh(),
            kh.getNgaysinh(),
            kh.getGhichu()
        });
    }
}

private void addSearchEvent() {
    txtSearch.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        @Override
        public void insertUpdate(javax.swing.event.DocumentEvent e) { try {
            search();
            } catch (SQLException ex) {
                System.getLogger(Khachhang.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
}

        @Override
        public void removeUpdate(javax.swing.event.DocumentEvent e) { try {
            search();
            } catch (SQLException ex) {
                System.getLogger(Khachhang.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
}

        @Override
        public void changedUpdate(javax.swing.event.DocumentEvent e) { try {
            search();
            } catch (SQLException ex) {
                System.getLogger(Khachhang.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
}
    });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachhang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        txtTenKH = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        cbGioitinh = new javax.swing.JComboBox<>();
        dtNgaySinh = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tarGhichu = new javax.swing.JTextArea();
        btnThem = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("Mã KH:");

        tblKhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachhangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachhang);

        jLabel2.setText("Tên KH:");

        jLabel3.setText("SDT:");

        jLabel4.setText("Địa chỉ:");

        jLabel5.setText("Giới tính:");

        jLabel6.setText("Ngày sinh:");

        jLabel7.setText("Ghi chú:");

        txtMaKH.setEnabled(false);

        cbGioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        dtNgaySinh.setDateFormatString("dd/MM/yyyy");

        tarGhichu.setColumns(20);
        tarGhichu.setRows(5);
        jScrollPane2.setViewportView(tarGhichu);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel8.setText("Tìm kiếm:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSDT)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbGioitinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(dtNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnThem)
                        .addGap(47, 47, 47)
                        .addComponent(btnUpdate)
                        .addGap(62, 62, 62)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
       try {
        KhachHang kh = new KhachHang();
        kh.setTenkh(txtTenKH.getText());
        kh.setSdt(txtSDT.getText());
        kh.setDiachi(txtDiaChi.getText());
        kh.setGioitinh(cbGioitinh.getSelectedItem().toString());
        kh.setNgaysinh(
            dtNgaySinh.getDate() == null ? null : new java.sql.Date(dtNgaySinh.getDate().getTime())
        );

        kh.setGhichu(tarGhichu.getText());

        if (controller.add(kh)) {
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            loadTable();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Lỗi thêm dữ liệu!");
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnThemActionPerformed

    private void tblKhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachhangMouseClicked
            int row=tblKhachhang.getSelectedRow();
            if(row>=0){
                txtMaKH.setText(tblKhachhang.getValueAt(row, 0).toString());
                txtTenKH.setText(tblKhachhang.getValueAt(row, 1).toString());
                txtSDT.setText(tblKhachhang.getValueAt(row, 2).toString());
                txtDiaChi.setText(tblKhachhang.getValueAt(row, 3).toString());
                cbGioitinh.setSelectedItem(tblKhachhang.getValueAt(row, 4));
                dtNgaySinh.setDate((Date) tblKhachhang.getValueAt(row, 5) );
                tarGhichu.setText(tblKhachhang.getValueAt(row, 6).toString());
            }
    }//GEN-LAST:event_tblKhachhangMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try{
            KhachHang kh=new KhachHang();
        kh.setMakh(Integer.parseInt(txtMaKH.getText()));
        kh.setTenkh(txtTenKH.getText());
        kh.setSdt(txtSDT.getText());
        kh.setDiachi(txtDiaChi.getText());
        kh.setGioitinh(cbGioitinh.getSelectedItem().toString());
        kh.setNgaysinh(
            dtNgaySinh.getDate() == null ? null : new java.sql.Date(dtNgaySinh.getDate().getTime())
        );
        kh.setGhichu(tarGhichu.getText());
        
        if(controller.update(kh)){
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            loadTable();
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Lỗi khi sửa dữ liệu");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row= tblKhachhang.getSelectedRow();
        if(row<0){
            JOptionPane.showMessageDialog(this, "Hãy chọn khách hàng cần xóa");
            return;
        }
        int confim=JOptionPane.showConfirmDialog(this, 
                "Bạn có chắc muốn xóa", "Xác nhận",
                JOptionPane.YES_NO_OPTION);
        if(confim==JOptionPane.YES_OPTION){
            int id=Integer.parseInt(tblKhachhang.getValueAt(row, 0).toString());
            try {
                if(controller.delete(id)){
                    loadTable();
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                }
            } catch (SQLException ex) {
                System.getLogger(Khachhang.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbGioitinh;
    private com.toedter.calendar.JDateChooser dtNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea tarGhichu;
    private javax.swing.JTable tblKhachhang;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTenKH;
    // End of variables declaration//GEN-END:variables
}
