/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.BacSiController;
import Controller.LichLamViecController;
import Model.DBConnection;
import Model.Entity.BacSi;
import Model.Entity.LichLamViec;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Time;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Time;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;




/**
 *
 * @author giang
 */
public class DoctorPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorPanel
     */
    public DoctorPanel() {
        initComponents();
        setPreferredSize(null); 
        loadTable();
        addSearchListener();

    }
       private void addSearchListener() {
    txtSearch.getDocument().addDocumentListener(new DocumentListener() {
        @Override
        public void insertUpdate(DocumentEvent e) { search(); }

        @Override
        public void removeUpdate(DocumentEvent e) { search(); }

        @Override
        public void changedUpdate(DocumentEvent e) { search(); }
    });
}

private void search() {
    String keyword = txtSearch.getText().trim();
    
    List<BacSi> list;
    if (keyword.isEmpty()) {
        list = controller.getAllBacSi();
    } else {
        list = controller.searchBacSi(keyword);
    }

    DefaultTableModel model = (DefaultTableModel) tblBacSi.getModel();
    model.setRowCount(0);

    for (BacSi bs : list) {
        List<LichLamViec> listLLV = lich.getLichLamViecByBacSi(bs.getId_bs());

        Date ngayBD = null;
        Date ngayKT = null;
        String gioBD = "";
        String gioKT = "";
        String thu = "";

        if (listLLV != null && !listLLV.isEmpty()) {
            Date minBD = listLLV.get(0).getNgaybatdau();
            Date maxKT = listLLV.get(0).getNgayketthuc();

            StringBuilder sbGioBD = new StringBuilder();
            StringBuilder sbGioKT = new StringBuilder();
            StringBuilder sbThu = new StringBuilder();

            for (LichLamViec llv : listLLV) {
                if (llv.getNgaybatdau().before(minBD)) minBD = llv.getNgaybatdau();
                if (llv.getNgayketthuc().after(maxKT)) maxKT = llv.getNgayketthuc();

                sbGioBD.append(llv.getGiobatdau()).append(" | ");
                sbGioKT.append(llv.getGioketthuc()).append(" | ");
                sbThu.append(llv.getThu()).append(", ");
            }

            ngayBD = minBD;
            ngayKT = maxKT;
            gioBD = sbGioBD.substring(0, sbGioBD.length() - 3);
            gioKT = sbGioKT.substring(0, sbGioKT.length() - 3);
            thu = sbThu.substring(0, sbThu.length() - 2);
        }

        model.addRow(new Object[]{
            bs.getId_bs(), bs.getHoten(), bs.getChuyenmon(),
            bs.getGioitinh(), bs.getNgaysinh(), bs.getSdt(),
            bs.getEmail(), bs.getDiachi(), bs.getGhichu(), bs.getTrangthai(),
            ngayBD, ngayKT, gioBD, gioKT, thu
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbGioiTinh = new javax.swing.JComboBox<>();
        cbChuyenMon = new javax.swing.JComboBox<>();
        jDateChooserNgaySinh = new com.toedter.calendar.JDateChooser();
        txtID = new javax.swing.JTextField();
        txtHoten = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cbTrangThai = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dtNgayBd = new com.toedter.calendar.JDateChooser();
        dtNgayKt = new com.toedter.calendar.JDateChooser();
        tpGioBd = new com.github.lgooddatepicker.components.TimePicker();
        tpGioKt = new com.github.lgooddatepicker.components.TimePicker();
        jLabel14 = new javax.swing.JLabel();
        chk2 = new javax.swing.JCheckBox();
        chk3 = new javax.swing.JCheckBox();
        chk4 = new javax.swing.JCheckBox();
        chk5 = new javax.swing.JCheckBox();
        chk6 = new javax.swing.JCheckBox();
        chk7 = new javax.swing.JCheckBox();
        chkCN = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRenew = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBacSi = new javax.swing.JTable();

        setBackground(new java.awt.Color(224, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin bác sĩ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel1.setText("Mã bác sĩ:");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setText("Họ tên:");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setText("Giới tính:");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setText("Ngày sinh:");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setText("Số điện thoại:");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setText("Email:");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setText("Chuyên khoa:");
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        cbChuyenMon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nội tổng quát", "Nhi khoa", "Sản phụ khoa", "Da liễu", "Tim mạch", "Tai mũi họng", "Nội tiết", "Cơ xương khớp" }));

        jDateChooserNgaySinh.setDateFormatString("dd/MM/yyyy");

        txtID.setEnabled(false);

        jLabel9.setText("Ghi chú:");
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setText("Địa chỉ:");
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel16.setText("Trạng thái:");

        cbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang làm việc", "Đã nghỉ việc" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtID)
                            .addComponent(txtHoten)
                            .addComponent(cbChuyenMon, 0, 192, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jDateChooserNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSDT)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                            .addComponent(txtDiaChi)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTrangThai, 0, 151, Short.MAX_VALUE)))
                .addGap(47, 47, 47))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6)
                        .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooserNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbChuyenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(cbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lịch làm viêc", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel10.setText("Ngày bắt đầu:");
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel11.setText("Ngày kết thúc:");
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel12.setText("Giờ bắt đầu:");
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel13.setText("Giờ kết thúc:");
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        dtNgayBd.setDateFormatString("dd/MM/yyyy");

        dtNgayKt.setDateFormatString("dd/MM/yyyy");

        jLabel14.setText("Thứ làm việc:");
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        chk2.setText("Thứ 2");

        chk3.setText("Thứ 3");

        chk4.setText("Thứ 4");

        chk5.setText("Thứ 5");
        chk5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk5ActionPerformed(evt);
            }
        });

        chk6.setText("Thứ 6");
        chk6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk6ActionPerformed(evt);
            }
        });

        chk7.setText("Thứ 7");

        chkCN.setText("Chủ nhật");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dtNgayBd, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(jLabel11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(tpGioBd, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dtNgayKt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tpGioKt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(chk2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chk3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chk4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chk5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chk6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chk7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkCN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11))
                            .addComponent(dtNgayBd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(tpGioKt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel12)
                                .addComponent(tpGioBd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(dtNgayKt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(chk2)
                    .addComponent(chk3)
                    .addComponent(chk4)
                    .addComponent(chk5)
                    .addComponent(chk6)
                    .addComponent(chk7)
                    .addComponent(chkCN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        btnAdd.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\add.png")); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\repair-tools.png")); // NOI18N
        btnUpdate.setText("Sửa");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\delete.png")); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnRenew.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\undo.png")); // NOI18N
        btnRenew.setText("Làm mới");
        btnRenew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenewActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\search.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addGap(29, 29, 29)
                .addComponent(btnUpdate)
                .addGap(33, 33, 33)
                .addComponent(btnDelete)
                .addGap(32, 32, 32)
                .addComponent(btnRenew)
                .addGap(52, 52, 52)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd)
                        .addComponent(btnUpdate)
                        .addComponent(btnDelete)
                        .addComponent(btnRenew)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách bác sĩ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        tblBacSi.setAutoCreateRowSorter(true);
        tblBacSi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBacSiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBacSi);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
     private BacSiController controller = new BacSiController();
     private LichLamViecController lich = new LichLamViecController();

     private void loadTable() {
         List<BacSi> list = controller.getAllBacSi();
         DefaultTableModel model = new DefaultTableModel();

         model.setColumnIdentifiers(new Object[] {
             "ID", "Họ tên", "Chuyên môn", "Giới tính",
             "Ngày sinh", "SĐT", "Email", "Địa chỉ", 
             "Ghi chú", "Trạng thái",
             "Ngày bắt đầu", "Ngày kết thúc",
             "Giờ bắt đầu", "Giờ kết thúc",
             "Thứ làm việc"
         });

         for (BacSi bs : list) {

             // Lấy tất cả lịch của bác sĩ
             List<LichLamViec> listLLV = lich.getLichLamViecByBacSi(bs.getId_bs());

             Date ngayBD = null;
             Date ngayKT =null;
             String gioBD = "";
             String gioKT = "";
             String thu = "";

             if (listLLV != null && !listLLV.isEmpty()) {

                 // Lấy ngày bắt đầu nhỏ nhất, ngày kết thúc lớn nhất
                 Date minBD = listLLV.get(0).getNgaybatdau();
                 Date maxKT = listLLV.get(0).getNgayketthuc();

                 StringBuilder sbGioBD = new StringBuilder();
                 StringBuilder sbGioKT = new StringBuilder();
                 StringBuilder sbThu = new StringBuilder();

                 for (LichLamViec llv : listLLV) {
                     // Tìm min / max ngày
                     if (llv.getNgaybatdau().before(minBD)) minBD = llv.getNgaybatdau();
                     if (llv.getNgayketthuc().after(maxKT)) maxKT = llv.getNgayketthuc();

                     sbGioBD.append(llv.getGiobatdau()).append(" | ");
                     sbGioKT.append(llv.getGioketthuc()).append(" | ");
                     sbThu.append(llv.getThu()).append(", ");
                 }

                 // Chuyển thành chuỗi
                 ngayBD = minBD;
                    ngayKT = maxKT;


                 gioBD = sbGioBD.substring(0, sbGioBD.length() - 3); // bỏ dấu | cuối
                 gioKT = sbGioKT.substring(0, sbGioKT.length() - 3); 
                 thu = sbThu.substring(0, sbThu.length() - 2);       // bỏ dấu , cuối
             }

             model.addRow(new Object[] {
                 bs.getId_bs(), bs.getHoten(), bs.getChuyenmon(),
                 bs.getGioitinh(), bs.getNgaysinh(), bs.getSdt(),
                 bs.getEmail(), bs.getDiachi(), bs.getGhichu(), bs.getTrangthai(),
                 ngayBD, ngayKT, gioBD, gioKT, thu
             });
         }

         tblBacSi.setModel(model);
     }


    private void chk5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk5ActionPerformed

    private void chk6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk6ActionPerformed
  
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       try {
        // --- VALIDATION ---
        if (txtHoten.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên bác sĩ không được để trống!");
            return;
        }

        if (jDateChooserNgaySinh.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Chọn ngày sinh!");
            return;
        }

        if (dtNgayBd.getDate() == null || dtNgayKt.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Chọn ngày bắt đầu và kết thúc!");
            return;
        }

        if (tpGioBd.getTime() == null || tpGioKt.getTime() == null) {
            JOptionPane.showMessageDialog(this, "Chọn giờ làm việc!");
            return;
        }

        // --- Lấy danh sách thứ làm việc ---
        List<String> thuList = new ArrayList<>();
        if (chk2.isSelected()) thuList.add("2");
        if (chk3.isSelected()) thuList.add("3");
        if (chk4.isSelected()) thuList.add("4");
        if (chk5.isSelected()) thuList.add("5");
        if (chk6.isSelected()) thuList.add("6");
        if (chk7.isSelected()) thuList.add("7");
        if (chkCN.isSelected()) thuList.add("CN");

        if (thuList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Chọn ít nhất một thứ làm việc!");
            return;
        }

        // --- TẠO BÁC SĨ ---
        BacSi bs = new BacSi();
        bs.setHoten(txtHoten.getText());
        bs.setChuyenmon(cbChuyenMon.getSelectedItem().toString());
        bs.setGioitinh(cbGioiTinh.getSelectedItem().toString());
        bs.setNgaysinh(jDateChooserNgaySinh.getDate());
        bs.setSdt(txtSDT.getText());
        bs.setEmail(txtEmail.getText());
        bs.setDiachi(txtDiaChi.getText());
        bs.setGhichu(txtGhiChu.getText());
        bs.setTrangthai(cbTrangThai.getSelectedItem().toString());

        // --- Thêm bác sĩ và lấy ID vừa tạo ---
        int idBS = controller.addBacSiReturnID(bs);

        if (idBS > 0) {
            // --- CHUYỂN NGÀY SANG java.sql.Date ---
            java.sql.Date ngayBD = new java.sql.Date(dtNgayBd.getDate().getTime());
            java.sql.Date ngayKT = new java.sql.Date(dtNgayKt.getDate().getTime());

            // --- CHUYỂN GIỜ TỪ LocalTime SANG java.sql.Time ---
            java.sql.Time sqlGioBD = java.sql.Time.valueOf(tpGioBd.getTime());
            java.sql.Time sqlGioKT = java.sql.Time.valueOf(tpGioKt.getTime());

            // --- THÊM LỊCH LÀM VIỆC ---
            for (String thu : thuList) {
                LichLamViec llv = new LichLamViec();
                llv.setId_bs(idBS);
                llv.setNgaybatdau(ngayBD);
                llv.setNgayketthuc(ngayKT);
                llv.setGiobatdau(sqlGioBD);
                llv.setGioketthuc(sqlGioKT);
                llv.setThu(thu);

                lich.addLichLamViec(llv);
            }

            loadTable();
            JOptionPane.showMessageDialog(this, "Thêm bác sĩ + lịch làm việc thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Thêm bác sĩ thất bại!");
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Có lỗi xảy ra!");
    }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblBacSiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBacSiMouseClicked
       int row = tblBacSi.getSelectedRow();
    if (row >= 0) {
        txtID.setText(tblBacSi.getValueAt(row, 0).toString());
        txtHoten.setText(tblBacSi.getValueAt(row, 1).toString());
        cbChuyenMon.setSelectedItem(tblBacSi.getValueAt(row, 2));
        cbGioiTinh.setSelectedItem(tblBacSi.getValueAt(row, 3));
        jDateChooserNgaySinh.setDate((Date) tblBacSi.getValueAt(row, 4));
        txtSDT.setText(tblBacSi.getValueAt(row, 5).toString());
        txtEmail.setText(tblBacSi.getValueAt(row, 6).toString());
        txtDiaChi.setText(tblBacSi.getValueAt(row, 7).toString());
        txtGhiChu.setText(tblBacSi.getValueAt(row, 8).toString());
        cbTrangThai.setSelectedItem(tblBacSi.getValueAt(row, 9));
        dtNgayBd.setDate((Date) tblBacSi.getValueAt(row, 10));
        dtNgayKt.setDate((Date) tblBacSi.getValueAt(row, 11));
       
        String gioBD = tblBacSi.getValueAt(row, 12).toString();
        if (!gioBD.isEmpty()) {
            String firstTime = gioBD.split("\\|")[0].trim();
            LocalTime lt = LocalTime.parse(firstTime);
            tpGioBd.setTime(lt);
        }

        String gioKT = tblBacSi.getValueAt(row, 13).toString();
        if (!gioKT.isEmpty()) {
            String firstTime = gioKT.split("\\|")[0].trim();
            LocalTime lt2 = LocalTime.parse(firstTime);
            tpGioKt.setTime(lt2);
        }

        String thuLamViec = tblBacSi.getValueAt(row, 14).toString();
        String[] arrThu = thuLamViec.split(",\\s*");

        chk2.setSelected(false);
        chk3.setSelected(false);
        chk4.setSelected(false);
        chk5.setSelected(false);
        chk6.setSelected(false);
        chk7.setSelected(false);
        chkCN.setSelected(false);

        for (String t : arrThu) {
            t = t.trim();

            // Nếu dữ liệu là dạng "Thứ 2,4,6"
            if (t.equals("2")) t = "Thứ 2";
            if (t.equals("3")) t = "Thứ 3";
            if (t.equals("4")) t = "Thứ 4";
            if (t.equals("5")) t = "Thứ 5";
            if (t.equals("6")) t = "Thứ 6";
            if (t.equals("7")) t = "Thứ 7";
            if (t.equalsIgnoreCase("CN")) t = "Chủ nhật";

            switch (t) {
                case "Thứ 2": chk2.setSelected(true); break;
                case "Thứ 3": chk3.setSelected(true); break;
                case "Thứ 4": chk4.setSelected(true); break;
                case "Thứ 5": chk5.setSelected(true); break;
                case "Thứ 6": chk6.setSelected(true); break;
                case "Thứ 7": chk7.setSelected(true); break;
                case "Chủ nhật": chkCN.setSelected(true); break;
            }
        }

        
        

    }
    }//GEN-LAST:event_tblBacSiMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
        int idBS = Integer.parseInt(txtID.getText());

        // --- VALIDATION giống phần Add ---
        if (txtHoten.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Tên bác sĩ không được để trống!");
            return;
        }

        // --- TẠO OBJECT BÁC SĨ ---
        BacSi bs = new BacSi();
        bs.setId_bs(idBS);
        bs.setHoten(txtHoten.getText());
        bs.setChuyenmon((String) cbChuyenMon.getSelectedItem());
        bs.setGioitinh((String) cbGioiTinh.getSelectedItem());
        bs.setNgaysinh(jDateChooserNgaySinh.getDate());
        bs.setSdt(txtSDT.getText());
        bs.setEmail(txtEmail.getText());
        bs.setDiachi(txtDiaChi.getText());
        bs.setGhichu(txtGhiChu.getText());
        bs.setTrangthai((String) cbTrangThai.getSelectedItem());

        boolean updated = controller.updateBacSi(bs);

        if (updated) {
            // 🧹 XÓA LỊCH CŨ
            lich.deleteLichLamViec(idBS);

            // THÊM LẠI LỊCH MỚI
            java.sql.Date ngayBD = new java.sql.Date(dtNgayBd.getDate().getTime());
            java.sql.Date ngayKT = new java.sql.Date(dtNgayKt.getDate().getTime());
            java.sql.Time gioBD = java.sql.Time.valueOf(tpGioBd.getTime());
            java.sql.Time gioKT = java.sql.Time.valueOf(tpGioKt.getTime());

            List<String> thuList = new ArrayList<>();
            if (chk2.isSelected()) thuList.add("2");
            if (chk3.isSelected()) thuList.add("3");
            if (chk4.isSelected()) thuList.add("4");
            if (chk5.isSelected()) thuList.add("5");
            if (chk6.isSelected()) thuList.add("6");
            if (chk7.isSelected()) thuList.add("7");
            if (chkCN.isSelected()) thuList.add("CN");

            for (String thu : thuList) {
                LichLamViec llv = new LichLamViec();
                llv.setId_bs(idBS);
                llv.setNgaybatdau(ngayBD);
                llv.setNgayketthuc(ngayKT);
                llv.setGiobatdau(gioBD);
                llv.setGioketthuc(gioKT);
                llv.setThu(thu);
                lich.addLichLamViec(llv);
            }

            loadTable();
            JOptionPane.showMessageDialog(this, "Cập nhật bác sĩ + lịch làm việc thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Cập nhật thất bại!");
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Có lỗi xảy ra!");
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
    int row = tblBacSi.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Hãy chọn bác sĩ cần xóa!");
        return;
    }
    int confirm = JOptionPane.showConfirmDialog(this,
        "Bạn có chắc muốn xóa bác sĩ này?",
        "Xác nhận",
        JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        int idBS = Integer.parseInt(tblBacSi.getValueAt(row, 0).toString());
        // Xóa lịch trước rồi xóa bác sĩ
        lich.deleteLlvBS(idBS);
        boolean success = controller.deleteBacSi(idBS);
        if (success) {
            loadTable();
            JOptionPane.showMessageDialog(this, "Xóa thành công!");
        } else {
            JOptionPane.showMessageDialog(this, "Xóa thất bại!");
        }
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRenewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenewActionPerformed
        txtID.setText("");
        txtHoten.setText("");
        txtDiaChi.setText("");
        txtEmail.setText("");
        txtGhiChu.setText("");
        txtSDT.setText("");
        cbChuyenMon.setSelectedIndex(0);
        cbGioiTinh.setSelectedIndex(0);
        jDateChooserNgaySinh.setDate(null);
        dtNgayBd.setDate(null);
        dtNgayKt.setDate(null);
        tpGioBd.setTime(null);
        tpGioKt.setTime(null);
        chk2.setSelected(false);
        chk3.setSelected(false);
        chk4.setSelected(false);
        chk5.setSelected(false);
        chk6.setSelected(false);
        chk7.setSelected(false);
        chkCN.setSelected(false);
        
    }//GEN-LAST:event_btnRenewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRenew;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbChuyenMon;
    private javax.swing.JComboBox<String> cbGioiTinh;
    private javax.swing.JComboBox<String> cbTrangThai;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JCheckBox chk3;
    private javax.swing.JCheckBox chk4;
    private javax.swing.JCheckBox chk5;
    private javax.swing.JCheckBox chk6;
    private javax.swing.JCheckBox chk7;
    private javax.swing.JCheckBox chkCN;
    private com.toedter.calendar.JDateChooser dtNgayBd;
    private com.toedter.calendar.JDateChooser dtNgayKt;
    private com.toedter.calendar.JDateChooser jDateChooserNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBacSi;
    private com.github.lgooddatepicker.components.TimePicker tpGioBd;
    private com.github.lgooddatepicker.components.TimePicker tpGioKt;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
