/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.Color;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.SwingUtilities;
import Model.Entity.UserSession;
/**
 *
 * @author giang
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());
    
    private String role;
    private int idRef;

    /**
     * Creates new form Patients
     */
    private DoctorPanel doctorPanel;
    private PatientsPanel patientsPanel;
    private MedicalAppointmentsPanel medicalPanel;
    private MedicinePanel medicinePanel;
    private InvoicePanel invoicePanel;
    private ServicePanel servicePanel;
    private EmployeesPanel employeesPanel;
    private ReportPanel reportPanel;
    private Account account;
    
    public MainFrame() {
        initComponents();
        jPanelContent.setLayout(new java.awt.CardLayout()); 
        doctorPanel = new DoctorPanel();
        patientsPanel = new PatientsPanel();
        medicalPanel = new MedicalAppointmentsPanel();
        medicinePanel = new MedicinePanel();
        invoicePanel = new InvoicePanel();
        servicePanel = new ServicePanel();
        employeesPanel = new EmployeesPanel();
        reportPanel = new ReportPanel();
        account =new Account();

        showPanel(patientsPanel);
    }
        private void showPanel(JPanel panel) {
            jPanelContent.removeAll();
            jPanelContent.add(panel);
            jPanelContent.revalidate();
            jPanelContent.repaint();
        }
        public MainFrame(String role) {
            this.role = role;

            initComponents();
            jPanelContent.setLayout(new java.awt.CardLayout()); 
            initPanels();
            hienThiNguoiDung();
            phanQuyenMenu();          
            showPanel(patientsPanel);
        }
        private void hienThiNguoiDung() {
    if (UserSession.isLoggedIn()) {
        txtHalo.setText("Xin chào, " + UserSession.getHoTen());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnPatients = new javax.swing.JLabel();
        btnMedical = new javax.swing.JLabel();
        btnMedicine = new javax.swing.JLabel();
        btnInvoice = new javax.swing.JLabel();
        btnService = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnDoctors = new javax.swing.JLabel();
        btnEmployees = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnReports = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAccount = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnSetting = new javax.swing.JButton();
        txtHalo = new javax.swing.JLabel();
        jPanelContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(224, 255, 255));

        btnPatients.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\patient.png")); // NOI18N
        btnPatients.setText("Patients");
        btnPatients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPatientsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPatientsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPatientsMouseExited(evt);
            }
        });

        btnMedical.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\calendar.png")); // NOI18N
        btnMedical.setText("Medical Appointments");
        btnMedical.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMedicalMouseClicked(evt);
            }
        });

        btnMedicine.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\medicine.png")); // NOI18N
        btnMedicine.setText("Medicine");
        btnMedicine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMedicineMouseClicked(evt);
            }
        });

        btnInvoice.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\bill.png")); // NOI18N
        btnInvoice.setText("Invoice");
        btnInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInvoiceMouseClicked(evt);
            }
        });

        btnService.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\service.png")); // NOI18N
        btnService.setText("Service");
        btnService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnServiceMouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\Check out_50px.png")); // NOI18N
        jLabel9.setText("Logout");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        btnDoctors.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\doctor.png")); // NOI18N
        btnDoctors.setText("Doctors");
        btnDoctors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDoctorsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDoctorsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDoctorsMouseExited(evt);
            }
        });

        btnEmployees.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\employee.png")); // NOI18N
        btnEmployees.setText("Employees");
        btnEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmployeesMouseClicked(evt);
            }
        });

        btnReports.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\analysis.png")); // NOI18N
        btnReports.setText("Reports");
        btnReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportsMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\giang\\OneDrive\\Tài liệu\\NetBeansProjects\\ClinicManagement\\src\\main\\resources\\medical_heh_care_doctor_hospital_icon_188998.png")); // NOI18N

        btnAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/user-list-icon.png"))); // NOI18N
        btnAccount.setText("Account");
        btnAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAccountMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPatients)
                            .addComponent(btnMedical)
                            .addComponent(btnMedicine)
                            .addComponent(btnInvoice)
                            .addComponent(btnService)
                            .addComponent(btnDoctors)
                            .addComponent(btnReports)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnAccount, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnEmployees, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel9)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPatients)
                .addGap(31, 31, 31)
                .addComponent(btnMedical)
                .addGap(31, 31, 31)
                .addComponent(btnDoctors)
                .addGap(29, 29, 29)
                .addComponent(btnMedicine)
                .addGap(31, 31, 31)
                .addComponent(btnInvoice)
                .addGap(31, 31, 31)
                .addComponent(btnService)
                .addGap(31, 31, 31)
                .addComponent(btnEmployees)
                .addGap(12, 12, 12)
                .addComponent(btnAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReports)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(224, 255, 255));

        jLabel2.setFont(new java.awt.Font("Garamond", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 255));
        jLabel2.setText("Clinic Management System");

        btnSetting.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\settings.png")); // NOI18N
        btnSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSettingMouseEntered(evt);
            }
        });

        txtHalo.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        txtHalo.setText("jLabel5");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179)
                .addComponent(txtHalo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnSetting)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSetting)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtHalo)))
                .addContainerGap())
        );

        jPanelContent.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContent.setPreferredSize(new java.awt.Dimension(824, 708));
        jPanelContent.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void initPanels() {
    doctorPanel = new DoctorPanel();
    patientsPanel = new PatientsPanel();
    medicalPanel = new MedicalAppointmentsPanel();
    medicinePanel = new MedicinePanel();
    invoicePanel = new InvoicePanel();
    servicePanel = new ServicePanel();
    employeesPanel = new EmployeesPanel();
    reportPanel = new ReportPanel();
    account=new Account();
    }
    private void phanQuyenMenu() {
        btnDoctors.setVisible(false);
        btnPatients.setVisible(false);
        btnMedical.setVisible(false);
        btnMedicine.setVisible(false);
        btnInvoice.setVisible(false);
        btnService.setVisible(false);
        btnEmployees.setVisible(false);
        btnReports.setVisible(false);
        btnAccount.setVisible(false);

        if (role == null) return;

        switch (role) {

            case "ADMIN":
                btnDoctors.setVisible(true);
                btnPatients.setVisible(true);
                btnMedical.setVisible(true);
                btnMedicine.setVisible(true);
                btnInvoice.setVisible(true);
                btnService.setVisible(true);
                btnEmployees.setVisible(true);
                btnReports.setVisible(true);
                btnAccount.setVisible(true);
                break;

            case "BACSI":
                btnPatients.setVisible(true);
                btnMedical.setVisible(true);
                break;

            case "NHANVIEN":
                btnMedical.setVisible(true);
                btnService.setVisible(true);
                btnInvoice.setVisible(true);
                break;
        }
    }

    private void btnDoctorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoctorsMouseClicked
                showPanel(doctorPanel);
    }//GEN-LAST:event_btnDoctorsMouseClicked

    private void btnDoctorsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoctorsMouseEntered
        // TODO add your handling code here:
        btnDoctors.setBackground(Color.red);
        btnDoctors.setOpaque(true);
    }//GEN-LAST:event_btnDoctorsMouseEntered

    private void btnDoctorsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDoctorsMouseExited
        // TODO add your handling code here:
        btnDoctors.setBackground(new Color(224,255,255));
    }//GEN-LAST:event_btnDoctorsMouseExited

    private void btnPatientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPatientsMouseClicked
       showPanel(patientsPanel);
    }//GEN-LAST:event_btnPatientsMouseClicked

    private void btnPatientsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPatientsMouseEntered
        // TODO add your handling code here:
               // TODO add your handling code here:
        btnPatients.setBackground(new Color(255,255,255));
        btnPatients.setOpaque(true);
    }//GEN-LAST:event_btnPatientsMouseEntered

    private void btnPatientsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPatientsMouseExited
        // TODO add your handling code here:
        btnPatients.setBackground(new Color(224,255,255));
    }//GEN-LAST:event_btnPatientsMouseExited

    private void btnMedicalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicalMouseClicked
         showPanel(medicalPanel);
    }//GEN-LAST:event_btnMedicalMouseClicked

    private void btnMedicineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMedicineMouseClicked
            showPanel(medicinePanel);
    }//GEN-LAST:event_btnMedicineMouseClicked

    private void btnInvoiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInvoiceMouseClicked
            showPanel(invoicePanel);
    }//GEN-LAST:event_btnInvoiceMouseClicked

    private void btnServiceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServiceMouseClicked
              showPanel(servicePanel);
    }//GEN-LAST:event_btnServiceMouseClicked

    private void btnEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmployeesMouseClicked
    showPanel(employeesPanel);
    }//GEN-LAST:event_btnEmployeesMouseClicked

    private void btnReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportsMouseClicked
            showPanel(reportPanel);
    }//GEN-LAST:event_btnReportsMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Login_Form l=new Login_Form();
        l.setVisible(true);
        UserSession.clear();
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btnSettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseEntered
  JPopupMenu popup = new JPopupMenu();

    JMenuItem dark = new JMenuItem("Dark mode");
    JMenuItem light = new JMenuItem("Light mode");
    JMenuItem changePass = new JMenuItem("Change Password");

    popup.add(dark);
    popup.add(light);
    popup.addSeparator();
    popup.add(changePass);

    dark.addActionListener(e -> {
        com.formdev.flatlaf.FlatDarkLaf.setup();
        SwingUtilities.updateComponentTreeUI(this);
    });

    light.addActionListener(e -> {
        com.formdev.flatlaf.FlatLightLaf.setup();
        SwingUtilities.updateComponentTreeUI(this);
    });

    // 👉 CHANGE PASSWORD
    changePass.addActionListener(e -> {
        ChangePasswordDialog dialog =
                new ChangePasswordDialog(this, true);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    });

    popup.show(btnSetting, 0, btnSetting.getHeight());
    }//GEN-LAST:event_btnSettingMouseEntered

    private void btnAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccountMouseClicked
        showPanel(account);
    }//GEN-LAST:event_btnAccountMouseClicked
    public PatientsPanel getPatientsPanel() {
    return patientsPanel;
}

public void showPatientsPanel(){
    showPanel(patientsPanel);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAccount;
    private javax.swing.JLabel btnDoctors;
    private javax.swing.JLabel btnEmployees;
    private javax.swing.JLabel btnInvoice;
    private javax.swing.JLabel btnMedical;
    private javax.swing.JLabel btnMedicine;
    private javax.swing.JLabel btnPatients;
    private javax.swing.JLabel btnReports;
    private javax.swing.JLabel btnService;
    private javax.swing.JButton btnSetting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanelContent;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel txtHalo;
    // End of variables declaration//GEN-END:variables
}
