/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.BacSiController;
import Controller.DatLichController;
import Controller.LichLamViecController;
import Model.DAO.BenhAnDAO;
import Model.DAO.BenhNhanDAO;
import Model.DAO.DatLichDAO;
import Model.DBConnection;
import Model.Entity.BacSi;
import Model.Entity.BenhAn;
import Model.Entity.BenhNhan;
import Model.Entity.DatLich;
import Model.Entity.LichLamViec;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalTime;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author giang
 */
public class MedicalAppointmentsPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicalAppointmentsPanel
     */
    public MedicalAppointmentsPanel() {
        initComponents();
        loadTable();
        loadComboBacSi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timegio = new com.github.lgooddatepicker.components.TimePicker();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        cbGioiTinh = new javax.swing.JComboBox<>();
        dateNgaySinh = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbBacsi = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnXemlich = new javax.swing.JButton();
        dateNgay = new com.toedter.calendar.JDateChooser();
        timeGio = new com.github.lgooddatepicker.components.TimePicker();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedical = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btnDatLich = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSaptoi = new javax.swing.JButton();
        btnVerify = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(824, 708));

        jPanel1.setBackground(new java.awt.Color(224, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin bệnh khám", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel1.setText("Họ và tên:");
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setText("Số điện thoại:");
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setText("Giới tính:");
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setText("Ngày sinh:");
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setText("Ghi chú:");
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        dateNgaySinh.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                            .addComponent(txtHoTen))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtGhiChu))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chọn bác sĩ & thời gian khám    ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel6.setText("Bác sĩ:");
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbBacsi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Ngày khám:");

        btnXemlich.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\search.png")); // NOI18N
        btnXemlich.setText("Xem lịch làm việc");
        btnXemlich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemlichActionPerformed(evt);
            }
        });

        dateNgay.setDateFormatString("dd/MM/yyyy");

        jLabel8.setText("Giờ:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbBacsi, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jLabel7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btnXemlich)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dateNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(timeGio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(cbBacsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addComponent(dateNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXemlich, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timeGio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lịch làm việc/ Lịch khám trong ngày của bác sĩ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        tblMedical.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblMedical.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMedicalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMedical);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnDatLich.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\reschedule.png")); // NOI18N
        btnDatLich.setText("Đặt lịch");
        btnDatLich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatLichActionPerformed(evt);
            }
        });

        btnUpdate.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\updated.png")); // NOI18N
        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\delete.png")); // NOI18N
        btnCancel.setText("Hủy lịch");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\undo.png")); // NOI18N
        btnReset.setText("Làm mới");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnSaptoi.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\clock.png")); // NOI18N
        btnSaptoi.setText("Sắp tới");
        btnSaptoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaptoiActionPerformed(evt);
            }
        });

        btnVerify.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/verified.png"))); // NOI18N
        btnVerify.setText("Xác nhận");
        btnVerify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnDatLich)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSaptoi)
                .addGap(18, 18, 18)
                .addComponent(btnReset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVerify)
                .addGap(57, 57, 57))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDatLich)
                    .addComponent(btnUpdate)
                    .addComponent(btnCancel)
                    .addComponent(btnReset)
                    .addComponent(btnSaptoi)
                    .addComponent(btnVerify, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    private BacSiController bacSiController = new BacSiController();
    private LichLamViecController lichController = new LichLamViecController();
    private DatLichController datlichctrl=new DatLichController();
    
    

    
    
    private void loadComboBacSi(){
   cbBacsi.removeAllItems();
   List<BacSi> list=bacSiController.getAllBacSi();
   
    for (BacSi bacSi : list) {
        cbBacsi.addItem(bacSi.getHoten());        
    }
 }
private BacSi getBacSiSelected(){
    String ten=cbBacsi.getSelectedItem().toString();
    for (BacSi bs : bacSiController.getAllBacSi()) {
        if(bs.getHoten().equals(ten)){
            return bs;
        }
        
    } return null;
}
private void loadTable() {

    List<BacSi> listBS = bacSiController.getAllBacSi();
    DefaultTableModel model = new DefaultTableModel();

    model.setColumnIdentifiers(new Object[]{
        "ID",
        "Họ tên",
        "Chuyên môn",
        "Trạng thái",
        "Ngày bắt đầu",
        "Ngày kết thúc",
        "Giờ làm việc",
        "Thứ làm việc"
    });

    for (BacSi bs : listBS) {

        List<LichLamViec> listLLV =
                lichController.getLichLamViecByBacSi(bs.getId_bs());

        Date ngayBD = null;
        Date ngayKT = null;
        String gioLam = "";
        String thuLam = "";

        if (listLLV != null && !listLLV.isEmpty()) {

            Date minBD = listLLV.get(0).getNgaybatdau();
            Date maxKT = listLLV.get(0).getNgayketthuc();

            StringBuilder sbGio = new StringBuilder();
            StringBuilder sbThu = new StringBuilder();

            for (LichLamViec llv : listLLV) {

                if (llv.getNgaybatdau().before(minBD)) {
                    minBD = llv.getNgaybatdau();
                }
                if (llv.getNgayketthuc().after(maxKT)) {
                    maxKT = llv.getNgayketthuc();
                }

                sbGio.append(llv.getGiobatdau())
                     .append(" - ")
                     .append(llv.getGioketthuc())
                     .append(" | ");

                sbThu.append(llv.getThu()).append(", ");
            }

            ngayBD = minBD;
            ngayKT = maxKT;

            // Bỏ ký tự thừa
            gioLam = sbGio.substring(0, sbGio.length() - 3);
            thuLam = sbThu.substring(0, sbThu.length() - 2);
        }

        model.addRow(new Object[]{
            bs.getId_bs(),
            bs.getHoten(),
            bs.getChuyenmon(),
            bs.getTrangthai(),
            ngayBD,
            ngayKT,
            gioLam,
            thuLam
        });
    }

    tblMedical.setModel(model);

    tblMedical.getColumnModel().getColumn(0).setMinWidth(0);
    tblMedical.getColumnModel().getColumn(0).setMaxWidth(0);
    tblMedical.getColumnModel().getColumn(0).setPreferredWidth(0);
}

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = tblMedical.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Chọn lịch cần cập nhật");
        return;
    }

    DatLich dl = new DatLich();

        int idLich = Integer.parseInt(
        tblMedical.getValueAt(row, 0).toString() // ✔️ GIỜ LÀ ID
    );
    dl.setId_lich(idLich);
    dl.setHoten_nv(txtHoTen.getText().trim());
    dl.setSdt_nv(txtSDT.getText().trim());
    dl.setGioitinh_nv(cbGioiTinh.getSelectedItem().toString());
    dl.setGhichu(txtGhiChu.getText().trim());

    if (dateNgaySinh.getDate() != null) {
        dl.setNgaysinh_nv(
            new java.sql.Date(dateNgaySinh.getDate().getTime())
        );
    }

    dl.setNgaykham(
        new java.sql.Date(dateNgay.getDate().getTime())
    );

    LocalTime lt = timeGio.getTime();
    if (lt != null) {
        dl.setGiokham(java.sql.Time.valueOf(lt));
    }

    BacSi bs = getBacSiSelected();
    dl.setId_bs(bs.getId_bs());

    boolean ok = datlichctrl.updateLich(dl);

    if (ok) {
        JOptionPane.showMessageDialog(this, "Cập nhật lịch thành công");
        hienThiLichTheoNgay();
    } else {
        JOptionPane.showMessageDialog(this, "Cập nhật thất bại");
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnXemlichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemlichActionPerformed
        hienThiLichTheoNgay();
    }//GEN-LAST:event_btnXemlichActionPerformed

    private void btnDatLichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatLichActionPerformed
      try {
        // ===== 1. LẤY DỮ LIỆU =====
        String hoTen = txtHoTen.getText().trim();
        String sdt = txtSDT.getText().trim();
        String gioiTinh = cbGioiTinh.getSelectedItem().toString();
        String ghiChu = txtGhiChu.getText().trim();

        java.util.Date utilNgaySinh = dateNgaySinh.getDate();
        java.util.Date utilNgayKham = dateNgay.getDate();

        if (hoTen.isEmpty() || sdt.isEmpty() || utilNgayKham == null) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin!");
            return;
        }

        java.sql.Date ngaySinh =
                (utilNgaySinh != null)
                        ? new java.sql.Date(utilNgaySinh.getTime())
                        : null;

        java.sql.Date ngayKham =
                new java.sql.Date(utilNgayKham.getTime());

        LocalTime lt = timeGio.getTime();
        java.sql.Time gioKham =
                (lt != null) ? java.sql.Time.valueOf(lt) : null;

        // ===== 2. LẤY BÁC SĨ =====
        BacSi bs = getBacSiSelected();
        if (bs == null) {
            JOptionPane.showMessageDialog(this, "Chưa chọn bác sĩ!");
            return;
        }

        // ===== 3. INSERT ĐẶT LỊCH (KHÔNG TẠO BỆNH NHÂN) =====
        String sql = """
            INSERT INTO DatLich
            (id_bn, hoten_nv, sdt_nv, gioitinh_nv, ngaysinh_nv,
             ghichu, id_bs, ngaykham, giokham)
            VALUES (?,?,?,?,?,?,?,?,?)
        """;

        try (Connection conn = DBConnection.getConnection();
             PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setNull(1, java.sql.Types.INTEGER); // ❗ id_bn = NULL
            ps.setString(2, hoTen);
            ps.setString(3, sdt);
            ps.setString(4, gioiTinh);
            ps.setDate(5, ngaySinh);
            ps.setString(6, ghiChu);
            ps.setInt(7, bs.getId_bs());
            ps.setDate(8, ngayKham);
            ps.setTime(9, gioKham);

            ps.executeUpdate();
        }

        // ===== 4. LOAD LẠI LỊCH =====
        loadLichTrongNgay(bs.getId_bs(), utilNgayKham);

        JOptionPane.showMessageDialog(this, "Đặt lịch thành công!");

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi đặt lịch!");
    }
    }//GEN-LAST:event_btnDatLichActionPerformed

    private void tblMedicalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMedicalMouseClicked
       
        int row=tblMedical.getSelectedRow();
       if(row>=0){
           txtHoTen.setText(tblMedical.getValueAt(row, 3).toString());
           txtSDT.setText(tblMedical.getValueAt(row, 4).toString());
           txtGhiChu.setText(tblMedical.getValueAt(row, 6).toString());
           cbGioiTinh.setSelectedItem(tblMedical.getValueAt(row, 5));
           dateNgay.setDate((java.util.Date) tblMedical.getValueAt(row, 1));
           java.sql.Time sqlTime =(java.sql.Time) tblMedical.getValueAt(row, 2);
            if (sqlTime != null) {
                timeGio.setTime(sqlTime.toLocalTime());
            }

       }
    }//GEN-LAST:event_tblMedicalMouseClicked

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        txtHoTen.setText("");
        txtGhiChu.setText("");
        txtSDT.setText("");
        dateNgaySinh.setDate(null);
        dateNgay.setDate(null);
        timeGio.setTime(null);
        loadTable();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int row = tblMedical.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Chọn lịch cần hủy");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Bạn có chắc muốn hủy lịch này?",
        "Xác nhận",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) return;

    // ⚠️ ID lịch phải là cột ID (ẩn)
    int idLich = Integer.parseInt(
        tblMedical.getValueAt(row, 0).toString()
    );

    boolean ok = datlichctrl.huyLich(idLich);

    if (ok) {
        JOptionPane.showMessageDialog(this, "Đã hủy lịch");

        // Reload lại bảng
        BacSi bs = getBacSiSelected();
        if (bs != null && dateNgay.getDate() != null) {
            loadLichTrongNgay(bs.getId_bs(), dateNgay.getDate());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Hủy lịch thất bại");
    }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaptoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaptoiActionPerformed
        java.util.Date utilDate = dateNgay.getDate();
    if (utilDate == null) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày");
        return;
    }

    java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

    List<Object[]> list = datlichctrl.getLichSapToi(sqlDate);

    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new Object[]{
        "ID",
        "Ngày khám",
        "Giờ khám",
        "Bệnh nhân",
        "SĐT",
        "Bác sĩ",
        "Trạng thái"
    });

    for (Object[] row : list) {
        model.addRow(row);
    }

    tblMedical.setModel(model);

    // Ẩn ID
    tblMedical.getColumnModel().getColumn(0).setMinWidth(0);
    tblMedical.getColumnModel().getColumn(0).setMaxWidth(0);
    tblMedical.getColumnModel().getColumn(0).setPreferredWidth(0);
    }//GEN-LAST:event_btnSaptoiActionPerformed

    private void btnVerifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyActionPerformed
    int row = tblMedical.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Chọn lịch cần xác nhận");
        return;
    }

    DatLich dl = new DatLich();
    dl.setHoten_nv(tblMedical.getValueAt(row, 3).toString());
    dl.setSdt_nv(tblMedical.getValueAt(row, 4).toString());
    dl.setTrangthai("Đã xác nhận");
    dl.setNgaykham((java.sql.Date) tblMedical.getValueAt(row, 1));
    dl.setGiokham((java.sql.Time) tblMedical.getValueAt(row, 2));

    // 🔥 LẤY MAINFRAME
    MainFrame main =
        (MainFrame) SwingUtilities.getWindowAncestor(this);

    // 🔥 TRUYỀN DỮ LIỆU
    main.getPatientsPanel().nhanDuLieuTuLich(dl);

    // 🔥 CHUYỂN PANEL
    main.showPatientsPanel();
    }//GEN-LAST:event_btnVerifyActionPerformed

    
    private void loadLichTrongNgay(int idBacSi, java.util.Date utilDate) {

    if (utilDate == null) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày khám");
        return;
    }

    // Convert util.Date -> sql.Date
    java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

    DefaultTableModel model = (DefaultTableModel) tblMedical.getModel();
    model.setRowCount(0);

    String sql = """
        SELECT dl.id_lich, dl.ngaykham, dl.giokham,
               bn.hoten, bn.sdt, dl.trangthai
        FROM DatLich dl
        LEFT JOIN BenhNhan bn ON dl.id_bn = bn.id_bn
        WHERE dl.id_bs = ? AND dl.ngaykham = ?
        ORDER BY dl.giokham
    """;

    try (Connection con = DBConnection.getConnection();
         PreparedStatement ps = con.prepareStatement(sql)) {

        ps.setInt(1, idBacSi);
        ps.setDate(2, sqlDate);

        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_lich"),
                rs.getDate("ngaykham"),
                rs.getTime("giokham"),
                rs.getString("hoten"),
                rs.getString("sdt"),
                rs.getString("trangthai")
            });
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi load lịch khám");
    }
}
    
private void hienThiLichTheoNgay() {

    BacSi bs = getBacSiSelected();
    if (bs == null) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn bác sĩ");
        return;
    }

    java.util.Date utilDate = dateNgay.getDate();
    if (utilDate == null) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày");
        return;
    }

    java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

    List<DatLich> list =
        datlichctrl.getLichTheoNgay(bs.getId_bs(), sqlDate);

    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new Object[]{
        "ID_LICH", 
        "Ngày khám",
        "Giờ khám",
        "Bệnh nhân",
        "SĐT",
        "Giới tính",
        "Trạng thái",
        "Ghi chú"
    });

    for (DatLich dl : list) {
        model.addRow(new Object[]{
            dl.getId_lich(),
            dl.getNgaykham(),
            dl.getGiokham(),
            dl.getHoten_nv(),
            dl.getSdt_nv(),
            dl.getGioitinh_nv(),
            dl.getTrangthai(),
            dl.getGhichu()
        });
    }

    tblMedical.setModel(model);
    
    tblMedical.getColumnModel().getColumn(0).setMinWidth(0);
    tblMedical.getColumnModel().getColumn(0).setMaxWidth(0);
    tblMedical.getColumnModel().getColumn(0).setPreferredWidth(0);

}





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDatLich;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSaptoi;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnVerify;
    private javax.swing.JButton btnXemlich;
    private javax.swing.JComboBox<String> cbBacsi;
    private javax.swing.JComboBox<String> cbGioiTinh;
    private com.toedter.calendar.JDateChooser dateNgay;
    private com.toedter.calendar.JDateChooser dateNgaySinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMedical;
    private com.github.lgooddatepicker.components.TimePicker timeGio;
    private com.github.lgooddatepicker.components.TimePicker timegio;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
}
