/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;
import Model.DBConnection;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.chart.ui.RectangleInsets;



/**
 *
 * @author giang
 */
public class ReportPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorPanel
     */
    public ReportPanel() {
        initComponents();
        setPreferredSize(null); // cho phép nó giãn full theo layout cha

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private java.sql.Date getFromDate() {
    return new java.sql.Date(dtpNgayBD.getDate().getTime());
}

private java.sql.Date getToDate() {
    return new java.sql.Date(dtpNgayKT.getDate().getTime());
}

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dtpNgayBD = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        dtpNgayKT = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        cboLoaiBC = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        btnXemBaocao = new javax.swing.JButton();
        btnResset = new javax.swing.JButton();
        btnXuatEx = new javax.swing.JButton();
        btnXuatPdf = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        pnlBarChart = new javax.swing.JPanel();
        pnlPieChart = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfor = new javax.swing.JTable();

        jScrollPane2.setViewportView(jTree1);

        setBackground(new java.awt.Color(224, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Báo cáo hoạt động phòng khám", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\clock.png")); // NOI18N
        jLabel1.setText("Chọn thời gian:");

        jLabel2.setText("Từ:");

        dtpNgayBD.setDateFormatString("dd/MM/yyyy");

        jLabel3.setText("Đến:");

        jLabel4.setText("Loại báo cáo:");

        cboLoaiBC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doanh thu", "Lượt khám", "Thuốc", "Dịch vụ", "Bác sĩ", "Nhân viên" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dtpNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dtpNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboLoaiBC, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(dtpNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dtpNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cboLoaiBC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnXemBaocao.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\bar-chart.png")); // NOI18N
        btnXemBaocao.setText("Xem báo cáo");
        btnXemBaocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemBaocaoActionPerformed(evt);
            }
        });

        btnResset.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\undo.png")); // NOI18N
        btnResset.setText("Làm mới");

        btnXuatEx.setIcon(new javax.swing.ImageIcon("D:\\Ảnh thiết kế\\Clinic Management\\printer.png")); // NOI18N
        btnXuatEx.setText("Xuất excel ");

        btnXuatPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/pdf.png"))); // NOI18N
        btnXuatPdf.setText("Xuất PDF");
        btnXuatPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatPdfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnXemBaocao)
                .addGap(73, 73, 73)
                .addComponent(btnXuatEx)
                .addGap(63, 63, 63)
                .addComponent(btnXuatPdf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnResset)
                .addGap(71, 71, 71))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnXuatEx, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnXemBaocao)
                                .addComponent(btnResset)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnXuatPdf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        pnlBarChart.setMaximumSize(new java.awt.Dimension(221, 211));
        pnlBarChart.setMinimumSize(new java.awt.Dimension(221, 211));
        pnlBarChart.setPreferredSize(new java.awt.Dimension(221, 211));
        pnlBarChart.setLayout(new java.awt.BorderLayout());

        pnlPieChart.setMaximumSize(new java.awt.Dimension(221, 211));
        pnlPieChart.setMinimumSize(new java.awt.Dimension(221, 211));
        pnlPieChart.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(pnlBarChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlPieChart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPieChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBarChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tblInfor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblInfor);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXuatPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatPdfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXuatPdfActionPerformed

    private void btnXemBaocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemBaocaoActionPerformed
         if (dtpNgayBD.getDate() == null || dtpNgayKT.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn khoảng thời gian");
        return;
    }

    String loai = cboLoaiBC.getSelectedItem().toString();

    switch (loai) {
        case "Doanh thu":
            reportDoanhThu();
            break;
        case "Lượt khám":
            reportLuotKham();
            break;
        case "Thuốc":
            reportThuoc();
            break;
        case "Dịch vụ":
            reportDichVu();
            break;
        case "Bác sĩ":
            reportBacSi();
            break;
        case "Nhân viên":
            reportNhanVien();
            break;
    }
    }//GEN-LAST:event_btnXemBaocaoActionPerformed
private void showChart(JPanel panel, JFreeChart chart) {
    ChartPanel cp = new ChartPanel(chart);
    cp.setPreferredSize(new Dimension(221, 211));
    cp.setMouseZoomable(false);
    cp.setPopupMenu(null);

    panel.removeAll();
    panel.setLayout(new BorderLayout());
    panel.add(cp, BorderLayout.CENTER);
    panel.revalidate();
    panel.repaint();
}
    private void reportDoanhThu() {

    loadBar_DoanhThu();
    loadPie_DoanhThu();
    loadTable_DoanhThu();
}
private void loadBar_DoanhThu() {

    DefaultCategoryDataset ds = new DefaultCategoryDataset();

    String sql = """
        SELECT CAST(ngaylap AS DATE) ngay, SUM(tongtien) doanhthu
        FROM HoaDon
        WHERE trangthai = N'Đã thanh toán'
          AND ngaylap BETWEEN ? AND ?
        GROUP BY CAST(ngaylap AS DATE)
        ORDER BY ngay
    """;

    try (Connection c = DBConnection.getConnection();
         PreparedStatement ps = c.prepareStatement(sql)) {

        ps.setDate(1, getFromDate());
        ps.setDate(2, getToDate());

        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            ds.addValue(
                rs.getDouble("doanhthu"),
                "Doanh thu",
                rs.getDate("ngay").toString()
            );
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    JFreeChart chart = ChartFactory.createBarChart(
        "Doanh thu theo ngày",
        null,
        null,
        ds
    );

    chart.removeLegend();
    chart.setPadding(new RectangleInsets(5,5,5,5));

    showChart(pnlBarChart, chart);
}
private void loadPie_DoanhThu() {

    DefaultPieDataset ds = new DefaultPieDataset();

    String sql = """
        SELECT loai_item, SUM(thanhtien) tong
        FROM ChiTiet_HoaDon cthd
        JOIN HoaDon hd ON cthd.id_hd = hd.id_hd
        WHERE hd.trangthai = N'Đã thanh toán'
          AND hd.ngaylap BETWEEN ? AND ?
        GROUP BY loai_item
    """;

    try (Connection c = DBConnection.getConnection();
         PreparedStatement ps = c.prepareStatement(sql)) {

        ps.setDate(1, getFromDate());
        ps.setDate(2, getToDate());

        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            ds.setValue(rs.getString("loai_item"), rs.getDouble("tong"));
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    JFreeChart chart = ChartFactory.createPieChart(
        "Cơ cấu doanh thu",
        ds,
        false,
        true,
        false
    );

    showChart(pnlPieChart, chart);
}
private void loadTable_DoanhThu() {

    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[]{
        "Ngày", "Mã HĐ", "Tổng tiền"
    });

    String sql = """
        SELECT mahd, CAST(ngaylap AS DATE) ngay, tongtien
        FROM HoaDon
        WHERE trangthai = N'Đã thanh toán'
          AND ngaylap BETWEEN ? AND ?
        ORDER BY ngaylap DESC
    """;

    try (Connection c = DBConnection.getConnection();
         PreparedStatement ps = c.prepareStatement(sql)) {

        ps.setDate(1, getFromDate());
        ps.setDate(2, getToDate());

        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getDate("ngay"),
                rs.getString("mahd"),
                rs.getDouble("tongtien")
            });
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    tblInfor.setModel(model);
}

private void reportLuotKham() {
    loadBar_LuotKham();
    loadPie_LuotKham();
    loadTable_LuotKham();
}

private void loadBar_LuotKham() {

    DefaultCategoryDataset ds = new DefaultCategoryDataset();

    String sql = """
        SELECT CAST(ngaykhamban AS DATE) ngay, COUNT(*) solan
        FROM PhieuKham
        WHERE ngaykhamban BETWEEN ? AND ?
        GROUP BY CAST(ngaykhamban AS DATE)
        ORDER BY ngay
    """;

    try (Connection c = DBConnection.getConnection();
         PreparedStatement ps = c.prepareStatement(sql)) {

        ps.setDate(1, getFromDate());
        ps.setDate(2, getToDate());

        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            ds.addValue(rs.getInt("solan"), "Lượt khám", rs.getDate("ngay").toString());
        }
    } catch (Exception e) { e.printStackTrace(); }

    JFreeChart chart = ChartFactory.createBarChart(
        "Lượt khám theo ngày", null, null, ds
    );
    chart.removeLegend();
    showChart(pnlBarChart, chart);
}
private void loadPie_LuotKham() {

    DefaultPieDataset ds = new DefaultPieDataset();

    String sql = """
        SELECT bs.hoten, COUNT(*) solan
        FROM PhieuKham pk
        JOIN BacSi bs ON pk.id_bs = bs.id_bs
        WHERE pk.ngaykhamban BETWEEN ? AND ?
        GROUP BY bs.hoten
    """;

    try (Connection c = DBConnection.getConnection();
         PreparedStatement ps = c.prepareStatement(sql)) {

        ps.setDate(1, getFromDate());
        ps.setDate(2, getToDate());

        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            ds.setValue(rs.getString("hoten"), rs.getInt("solan"));
        }
    } catch (Exception e) { e.printStackTrace(); }

    JFreeChart chart = ChartFactory.createPieChart(
        "Lượt khám theo bác sĩ", ds, false, true, false
    );
    showChart(pnlPieChart, chart);
}
private void loadTable_LuotKham() {

    DefaultTableModel m = new DefaultTableModel();
    m.setColumnIdentifiers(new String[]{"Ngày", "Bệnh nhân", "Bác sĩ", "Trạng thái"});

    String sql = """
        SELECT CAST(pk.ngaykhamban AS DATE) ngay,
               bn.hoten bn, bs.hoten bs, pk.trangthai
        FROM PhieuKham pk
        JOIN BenhNhan bn ON pk.id_bn = bn.id_bn
        JOIN BacSi bs ON pk.id_bs = bs.id_bs
        WHERE pk.ngaykhamban BETWEEN ? AND ?
        ORDER BY pk.ngaykhamban DESC
    """;

    try (Connection c = DBConnection.getConnection();
         PreparedStatement ps = c.prepareStatement(sql)) {

        ps.setDate(1, getFromDate());
        ps.setDate(2, getToDate());

        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            m.addRow(new Object[]{
                rs.getDate("ngay"),
                rs.getString("bn"),
                rs.getString("bs"),
                rs.getString("trangthai")
            });
        }
    } catch (Exception e) { e.printStackTrace(); }

    tblInfor.setModel(m);
}
private void reportThuoc() {
    loadBar_Thuoc();
    loadPie_Thuoc();
    loadTable_Thuoc();
}

private void loadBar_Thuoc() {

    DefaultCategoryDataset ds = new DefaultCategoryDataset();

    String sql = """
        SELECT t.tenthuoc, SUM(ct.soluong) sl
        FROM ChiTiet_DonThuoc ct
        JOIN Thuoc t ON ct.id_thuoc = t.id_thuoc
        JOIN DonThuoc dt ON ct.id_dt = dt.id_dt
        WHERE dt.ngaylap BETWEEN ? AND ?
        GROUP BY t.tenthuoc
    """;

    try (Connection c = DBConnection.getConnection();
         PreparedStatement ps = c.prepareStatement(sql)) {

        ps.setDate(1, getFromDate());
        ps.setDate(2, getToDate());

        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            ds.addValue(rs.getInt("sl"), "Thuốc", rs.getString("tenthuoc"));
        }
    } catch (Exception e) { e.printStackTrace(); }

    JFreeChart chart = ChartFactory.createBarChart("Thuốc bán", null, null, ds);
    chart.removeLegend();
    showChart(pnlBarChart, chart);
}
private void loadPie_Thuoc() {
    DefaultPieDataset ds = new DefaultPieDataset();
    String sql = """
        SELECT TOP 5 t.tenthuoc, SUM(ct.soluong) sl
        FROM ChiTiet_DonThuoc ct
        JOIN Thuoc t ON ct.id_thuoc = t.id_thuoc
        JOIN DonThuoc dt ON ct.id_dt = dt.id_dt
        WHERE dt.ngaylap BETWEEN ? AND ?
        GROUP BY t.tenthuoc
        ORDER BY sl DESC
    """;

    try (Connection c = DBConnection.getConnection();
         PreparedStatement ps = c.prepareStatement(sql)) {

        ps.setDate(1, getFromDate());
        ps.setDate(2, getToDate());
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            ds.setValue(rs.getString("tenthuoc"), rs.getInt("sl"));
        }
    } catch (Exception e) { e.printStackTrace(); }

    showChart(pnlPieChart, ChartFactory.createPieChart("Top thuốc", ds, false, true, false));
}
private void loadTable_Thuoc() {

    DefaultTableModel m = new DefaultTableModel();
    m.setColumnIdentifiers(new String[]{"Tên thuốc", "Số lượng", "Đơn vị"});

    String sql = """
        SELECT t.tenthuoc, SUM(ct.soluong) sl, t.donvitinh
        FROM ChiTiet_DonThuoc ct
        JOIN Thuoc t ON ct.id_thuoc = t.id_thuoc
        JOIN DonThuoc dt ON ct.id_dt = dt.id_dt
        WHERE dt.ngaylap BETWEEN ? AND ?
        GROUP BY t.tenthuoc, t.donvitinh
    """;

    try (Connection c = DBConnection.getConnection();
         PreparedStatement ps = c.prepareStatement(sql)) {

        ps.setDate(1, getFromDate());
        ps.setDate(2, getToDate());

        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            m.addRow(new Object[]{
                rs.getString("tenthuoc"),
                rs.getInt("sl"),
                rs.getString("donvitinh")
            });
        }
    } catch (Exception e) { e.printStackTrace(); }

    tblInfor.setModel(m);
}


private void reportDichVu() {
    loadBar_DichVu();
    loadPie_DichVu();
    loadTable_DichVu();
}
private void loadBar_DichVu() {

    DefaultCategoryDataset ds = new DefaultCategoryDataset();

    String sql = """
        SELECT dv.tendv, COUNT(*) sl
        FROM ChiTiet_DichVu ct
        JOIN DichVu dv ON ct.id_dv = dv.id_dv
        JOIN BenhAn ba ON ct.id_ba = ba.id_ba
        WHERE ba.ngaykhambenhan BETWEEN ? AND ?
        GROUP BY dv.tendv
    """;

    try (Connection c = DBConnection.getConnection();
         PreparedStatement ps = c.prepareStatement(sql)) {

        ps.setDate(1, getFromDate());
        ps.setDate(2, getToDate());

        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            ds.addValue(
                rs.getInt("sl"),
                "Dịch vụ",
                rs.getString("tendv")
            );
        }

    } catch (Exception e) {
        e.printStackTrace();
    }

    JFreeChart chart = ChartFactory.createBarChart(
        "Số lượt sử dụng dịch vụ",
        null,
        null,
        ds
    );

    chart.removeLegend();
    showChart(pnlBarChart, chart);
}
private void loadPie_DichVu() {

    DefaultPieDataset ds = new DefaultPieDataset();

    String sql = """
        SELECT TOP 5 dv.tendv, COUNT(*) sl
        FROM ChiTiet_DichVu ct
        JOIN DichVu dv ON ct.id_dv = dv.id_dv
        JOIN BenhAn ba ON ct.id_ba = ba.id_ba
        WHERE ba.ngaykhambenhan BETWEEN ? AND ?
        GROUP BY dv.tendv
        ORDER BY sl DESC
    """;

    try (Connection c = DBConnection.getConnection();
         PreparedStatement ps = c.prepareStatement(sql)) {

        ps.setDate(1, getFromDate());
        ps.setDate(2, getToDate());

        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            ds.setValue(
                rs.getString("tendv"),
                rs.getInt("sl")
            );
        }

    } catch (Exception e) {
        e.printStackTrace();
    }

    showChart(
        pnlPieChart,
        ChartFactory.createPieChart(
            "Top dịch vụ",
            ds,
            false,
            true,
            false
        )
    );
}
private void loadTable_DichVu() {

    DefaultTableModel m = new DefaultTableModel();
    m.setColumnIdentifiers(new String[]{
        "Tên dịch vụ",
        "Số lượt",
        "Đơn giá",
        "Doanh thu"
    });

    String sql = """
        SELECT dv.tendv,
               COUNT(*) sl,
               dv.dongia,
               COUNT(*) * dv.dongia doanhthu
        FROM ChiTiet_DichVu ct
        JOIN DichVu dv ON ct.id_dv = dv.id_dv
        JOIN BenhAn ba ON ct.id_ba = ba.id_ba
        WHERE ba.ngaykhambenhan BETWEEN ? AND ?
        GROUP BY dv.tendv, dv.dongia
    """;

    try (Connection c = DBConnection.getConnection();
         PreparedStatement ps = c.prepareStatement(sql)) {

        ps.setDate(1, getFromDate());
        ps.setDate(2, getToDate());

        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            m.addRow(new Object[]{
                rs.getString("tendv"),
                rs.getInt("sl"),
                rs.getBigDecimal("dongia"),
                rs.getBigDecimal("doanhthu")
            });
        }

    } catch (Exception e) {
        e.printStackTrace();
    }

    tblInfor.setModel(m);
}

private void reportBacSi() {
    loadBar_BacSi();
    loadPie_BacSi();
    loadTable_BacSi();
}
private void loadBar_BacSi() {

    DefaultCategoryDataset ds = new DefaultCategoryDataset();

    String sql = """
        SELECT bs.hoten, COUNT(*) AS songay
        FROM LichLamViec llv
        JOIN BacSi bs ON llv.id_bs = bs.id_bs
        WHERE llv.ngaybatdau >= ? AND llv.ngayketthuc <= ?
        GROUP BY bs.hoten
    """;

    try (Connection c = DBConnection.getConnection();
         PreparedStatement ps = c.prepareStatement(sql)) {

        ps.setDate(1, getFromDate());
        ps.setDate(2, getToDate());

        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            ds.addValue(
                rs.getInt("songay"),
                "Bác sĩ",
                rs.getString("hoten")
            );
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    JFreeChart chart = ChartFactory.createBarChart(
        "Số ngày làm việc của bác sĩ",
        null,
        null,
        ds
    );

    chart.removeLegend();
    showChart(pnlBarChart, chart);
}
private void loadPie_BacSi() {

    DefaultPieDataset ds = new DefaultPieDataset();

    String sql = """
        SELECT chuyenmon, COUNT(*) sl
        FROM BacSi
        WHERE trangthai = N'Đang làm việc'
        GROUP BY chuyenmon
    """;

    try (Connection c = DBConnection.getConnection();
         PreparedStatement ps = c.prepareStatement(sql)) {

        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            ds.setValue(
                rs.getString("chuyenmon"),
                rs.getInt("sl")
            );
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    showChart(
        pnlPieChart,
        ChartFactory.createPieChart(
            "Tỷ lệ bác sĩ theo chuyên môn",
            ds,
            false,
            true,
            false
        )
    );
}
private void loadTable_BacSi() {

    DefaultTableModel m = new DefaultTableModel();
    m.setColumnIdentifiers(new String[]{
        "Họ tên",
        "Chuyên môn",
        "Giới tính",
        "SĐT",
        "Trạng thái"
    });

    String sql = """
        SELECT hoten, chuyenmon, gioitinh, sdt, trangthai
        FROM BacSi
    """;

    try (Connection c = DBConnection.getConnection();
         PreparedStatement ps = c.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            m.addRow(new Object[]{
                rs.getString("hoten"),
                rs.getString("chuyenmon"),
                rs.getString("gioitinh"),
                rs.getString("sdt"),
                rs.getString("trangthai")
            });
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    tblInfor.setModel(m);
}
private void reportNhanVien() {
    loadBar_NhanVien();
    loadPie_NhanVien();
    loadTable_NhanVien();
}
private void loadBar_NhanVien() {

    DefaultCategoryDataset ds = new DefaultCategoryDataset();

    String sql = """
        SELECT chucvu, COUNT(*) sl
        FROM NhanVien
        GROUP BY chucvu
    """;

    try (Connection c = DBConnection.getConnection();
         PreparedStatement ps = c.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            ds.addValue(
                rs.getInt("sl"),
                "Nhân viên",
                rs.getString("chucvu")
            );
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    JFreeChart chart = ChartFactory.createBarChart(
        "Số lượng nhân viên theo chức vụ",
        null,
        null,
        ds
    );

    chart.removeLegend();
    showChart(pnlBarChart, chart);
}
private void loadPie_NhanVien() {

    DefaultPieDataset ds = new DefaultPieDataset();

    String sql = """
        SELECT trangthai, COUNT(*) sl
        FROM NhanVien
        GROUP BY trangthai
    """;

    try (Connection c = DBConnection.getConnection();
         PreparedStatement ps = c.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            ds.setValue(
                rs.getString("trangthai"),
                rs.getInt("sl")
            );
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    showChart(
        pnlPieChart,
        ChartFactory.createPieChart(
            "Trạng thái nhân viên",
            ds,
            false,
            true,
            false
        )
    );
}
private void loadTable_NhanVien() {

    DefaultTableModel m = new DefaultTableModel();
    m.setColumnIdentifiers(new String[]{
        "Họ tên",
        "Chức vụ",
        "Giới tính",
        "SĐT",
        "Trạng thái"
    });

    String sql = """
        SELECT hoten, chucvu, gioitinh, sdt, trangthai
        FROM NhanVien
    """;

    try (Connection c = DBConnection.getConnection();
         PreparedStatement ps = c.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            m.addRow(new Object[]{
                rs.getString("hoten"),
                rs.getString("chucvu"),
                rs.getString("gioitinh"),
                rs.getString("sdt"),
                rs.getString("trangthai")
            });
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    tblInfor.setModel(m);
}





    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResset;
    private javax.swing.JButton btnXemBaocao;
    private javax.swing.JButton btnXuatEx;
    private javax.swing.JButton btnXuatPdf;
    private javax.swing.JComboBox<String> cboLoaiBC;
    private com.toedter.calendar.JDateChooser dtpNgayBD;
    private com.toedter.calendar.JDateChooser dtpNgayKT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JPanel pnlBarChart;
    private javax.swing.JPanel pnlPieChart;
    private javax.swing.JTable tblInfor;
    // End of variables declaration//GEN-END:variables
}
